### ISSUE TITLE
`npm run build-doc` throws an error

### ISSUE THREAD

**Issue by pmario** [nextcloud/cdav-library#577]
OS: ubuntu 20.04 LTS
node: 16.13.0
make: GNU Make 4.2.1

running `npm run build-doc` throws the following error: 

```
output: /home/mario/cdav-library/docs/class/src/models/addressBookHome.js~AddressBookHome.html
output: /home/mario/cdav-library/docs/class/src/errors/attachError.js~AttachError.html
output: /home/mario/cdav-library/docs/class/src/models/calendar.js~Calendar.html

SyntaxError: Invalid regular expression: /[~](Calendar$/: Unterminated group
    at new RegExp (<anonymous>)
    at ClassDocBuilder._findByName (/home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:116:20)
    at ClassDocBuilder._buildDocLinkHTML (/home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:782:22)
    at ClassDocBuilder._buildTypeDocLinkHTML (/home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:764:19)
    at /home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:743:23
    at Array.map (<anonymous>)
    at /home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:741:29
    at Array.map (<anonymous>)
    at ClassDocBuilder._buildTypeDocLinkHTML (/home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:740:43)
    at ClassDocBuilder._buildSignatureHTML (/home/mario/cdav-library/node_modules/esdoc-publish-html-plugin/out/src/Builder/DocBuilder.js:860:36)

```

**Comment by st3iny** [comment]
This is reported upstream at https://github.com/esdoc/esdoc-plugins/issues/29. It does not seem that esdoc is actively maintained anymore.

**Comment by st3iny** [comment]
The script has been dropped as esdoc seems to be orphaned and is broken.
